### ISSUE TITLE
Cant start

### ISSUE THREAD

**Issue by ghost** [lveez/bo1-debugger#1]
me and others cant get it to start/inject when following the installation guide from the readme, it seems to be missing some files:

![image](https://github.com/user-attachments/assets/ed02fea4-c412-4be2-8027-d43f41be237d)

![image](https://github.com/user-attachments/assets/12f9545a-40c3-4600-86fa-55cd82dcc600)

**Comment by lveez** [comment]
Pretty sure this is a bug with the g++ I use (or maybe you're just supposed to use gcc even with c++). But yeah I forgot to link the std libs when compiling.

Honestly would recommend just downloading a DLL injector from online somewhere, any old one will work, and hopefully the DLL is linked correctly. I don't have any compilers for windows on my PC anymore but if it doesn't work with a different injector I'll see if I can build it for windows from linux or something.

**Comment by ghost** [comment]
yea even when injecting with process hacker or just any other injector it doesnt seem to do anything

**Comment by lveez** [comment]
Not sure why it isn't working tbh, in the makefile I use `-shared` which should link it with standard libs statically I believe. 

Quickest solution I have for you if you really want to use this and are willing to install the toolchain I used is the following:

- Install MSYS2
- Open MSYS2 and run the following commands:
- Run `pacman -Syu`
- Run `pacman -S mingw-w64-i686-gcc`
- Run `pacman -Syu` again

This is a pretty bad solution but I can try and fix it properly in the future when I get a chance. You might have to also add `C:\msys2\mingw32\bin` (or wherever you installed msys2) to path.

After doing this the DLL (and injector) will work.

**Comment by lveez** [comment]
Actually ignore this I will send you the DLLs in discord to test if that works, bit of a nicer solution if it does.

**Comment by lveez** [comment]
Added DLLs and fixed `bo1-debugger.dll` in [this](https://github.com/lveez/bo1-debugger/releases/tag/1.0(fixed)) release.
